export const CIUDADES = [
  // Buenos Aires - CABA
  'Buenos Aires, CABA',
  // Buenos Aires - GBA
  'La Plata, Buenos Aires',
  'Mar del Plata, Buenos Aires',
  'Bahía Blanca, Buenos Aires',
  'Quilmes, Buenos Aires',
  'Lanús, Buenos Aires',
  'Lomas de Zamora, Buenos Aires',
  'Almirante Brown, Buenos Aires',
  'Florencio Varela, Buenos Aires',
  'Tres de Febrero, Buenos Aires',
  'Morón, Buenos Aires',
  'Merlo, Buenos Aires',
  'Tigre, Buenos Aires',
  'Pilar, Buenos Aires',
  'San Isidro, Buenos Aires',
  'Vicente López, Buenos Aires',
  'General San Martín, Buenos Aires',
  'Malvinas Argentinas, Buenos Aires',
  'José C. Paz, Buenos Aires',
  'San Miguel, Buenos Aires',
  'Campana, Buenos Aires',
  'Zárate, Buenos Aires',
  'Tandil, Buenos Aires',
  'Pergamino, Buenos Aires',
  'Junín, Buenos Aires',
  'Necochea, Buenos Aires',
  'Olavarría, Buenos Aires',
  // Catamarca
  'San Fernando del Valle, Catamarca',
  'Catamarca Capital, Catamarca',
  'Valle Viejo, Catamarca',
  'Fray Mamerto Esquiú, Catamarca',
  'Tinogasta, Catamarca',
  'Andalgalá, Catamarca',
  // Chaco
  'Resistencia, Chaco',
  'Presidencia Roque Sáenz Peña, Chaco',
  'Villa Ángela, Chaco',
  // Chubut
  'Comodoro Rivadavia, Chubut',
  'Trelew, Chubut',
  'Puerto Madryn, Chubut',
  'Esquel, Chubut',
  'Rawson, Chubut',
  // Córdoba
  'Córdoba Capital, Córdoba',
  'Villa María, Córdoba',
  'Río Cuarto, Córdoba',
  'San Francisco, Córdoba',
  'Villa Carlos Paz, Córdoba',
  'Alta Gracia, Córdoba',
  'Cosquín, Córdoba',
  'La Falda, Córdoba',
  'Jesús María, Córdoba',
  'Bell Ville, Córdoba',
  // Corrientes
  'Corrientes Capital, Corrientes',
  'Goya, Corrientes',
  'Paso de los Libres, Corrientes',
  'Mercedes, Corrientes',
  // Entre Ríos
  'Paraná, Entre Ríos',
  'Concordia, Entre Ríos',
  'Gualeguaychú, Entre Ríos',
  'Colón, Entre Ríos',
  'Concepción del Uruguay, Entre Ríos',
  // Formosa
  'Formosa Capital, Formosa',
  'Clorinda, Formosa',
  // Jujuy
  'San Salvador de Jujuy, Jujuy',
  'Palpalá, Jujuy',
  'Libertador General San Martín, Jujuy',
  'San Pedro de Jujuy, Jujuy',
  // La Pampa
  'Santa Rosa, La Pampa',
  'General Pico, La Pampa',
  // La Rioja
  'La Rioja Capital, La Rioja',
  'Chilecito, La Rioja',
  // Mendoza
  'Mendoza Capital, Mendoza',
  'San Rafael, Mendoza',
  'Godoy Cruz, Mendoza',
  'Luján de Cuyo, Mendoza',
  'Maipú, Mendoza',
  'Rivadavia, Mendoza',
  // Misiones
  'Posadas, Misiones',
  'Oberá, Misiones',
  'Eldorado, Misiones',
  'Puerto Iguazú, Misiones',
  // Neuquén
  'Neuquén Capital, Neuquén',
  'San Martín de los Andes, Neuquén',
  'Zapala, Neuquén',
  'Cutral Có, Neuquén',
  'Centenario, Neuquén',
  // Río Negro
  'San Carlos de Bariloche, Río Negro',
  'Cipolletti, Río Negro',
  'General Roca, Río Negro',
  'Viedma, Río Negro',
  'Allen, Río Negro',
  // Salta
  'Salta Capital, Salta',
  'San Ramón de la Nueva Orán, Salta',
  'Tartagal, Salta',
  'Güemes, Salta',
  'Metán, Salta',
  // San Juan
  'San Juan Capital, San Juan',
  'Rivadavia, San Juan',
  'Caucete, San Juan',
  // San Luis
  'San Luis Capital, San Luis',
  'Villa Mercedes, San Luis',
  // Santa Cruz
  'Río Gallegos, Santa Cruz',
  'Caleta Olivia, Santa Cruz',
  'El Calafate, Santa Cruz',
  // Santa Fe
  'Rosario, Santa Fe',
  'Santa Fe Capital, Santa Fe',
  'Rafaela, Santa Fe',
  'Venado Tuerto, Santa Fe',
  'Reconquista, Santa Fe',
  'Santo Tomé, Santa Fe',
  // Santiago del Estero
  'Santiago del Estero Capital, Santiago del Estero',
  'La Banda, Santiago del Estero',
  'Termas de Río Hondo, Santiago del Estero',
  // Tierra del Fuego
  'Ushuaia, Tierra del Fuego',
  'Río Grande, Tierra del Fuego',
  // Tucumán
  'San Miguel de Tucumán, Tucumán',
  'Tafí Viejo, Tucumán',
  'Yerba Buena, Tucumán',
  'Concepción, Tucumán',
  'Aguilares, Tucumán',
]
